### ISSUE TITLE
Fails with 'Could not open input file: composer-setup.php'

### ISSUE THREAD

**Issue by jamescrowley** [michaelw90/PHP-Lint#1]
I'm trying out these Actions, but this doesn't appear to work. You can see the log here: https://github.com/boxwise/dropapp/pull/141/checks?check_run_id=202799303

**Comment by sebastinez** [comment]
I ran into the same issue, trying out this Action on a pull request.
Log here: https://github.com/sebastinez/php-lint-action/commit/2d59da55cd06207c8cf606a4d2e07dc586cb59c6/checks

**Comment by laurentksh** [comment]
I'm getting the same error.

**Comment by sebastinez** [comment]
@michaelw90 Please attend this issue, since not doing so prevents the correct use of your otherwise great implementation for GitHub Actions...

**Comment by twovay** [comment]
while you can use https://github.com/awanesia/PHP-Lint
and I've tried https://github.com/awanesia/Trial-PHP-Lint

**Comment by bensebborn** [comment]
+1

**Comment by t73biz** [comment]
Perhaps a better solution is to simply include the package in your composer dev requirements
`composer require overtrue/phplint --dev`.

 I did this and then added to my testing.yml where we already use phpunit, a step definition:
```
    - name: PHP Lint
      run: vendor/bin/phplint
```

Also, adding a .phplint.yml seems to be the best solution, rather than a long line in the step definition

**Comment by szolll** [comment]
Same issue as mentioned above.

**Comment by laurentksh** [comment]
Yeah well @michaelw90 doesn't seem to give a sh*t about this project so you better use another linter.

**Comment by michaelw90** [comment]
Sorry for being a bit useless, I've updated v1, but also today pushed v2 to the Marketplace. 

https://github.com/michaelw90/PHP-Lint/releases/tag/2.0.0
https://github.com/marketplace/actions/php-lint

Again, huge apologies, but also, please be nice in the comments, I'm only (a busy) human like others. 

Stay safe + happy linting all. 👍
