### ISSUE TITLE
Could not open input file: composer-setup.php

### ISSUE THREAD

**Issue by JesseChua94** [michaelw90/PHP-Lint#14]
Hi, 

I'm running into an issue where the build fails when running the github action.

```
Step 4/11 : RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
 ---> Using cache
 ---> bc597164f15e
Step 5/11 : RUN php composer-setup.php
 ---> Running in 2fe92ef57d8b
The command '/bin/sh -c php composer-setup.php' returned a non-zero code: 1
Could not open input file: composer-setup.php
##[error]Docker build failed with exit code 1
```

**Comment by pramser** [comment]
Could the SHA be out of date for the installer? Looks like the Composer install page lists the tool as being updated on July 2, 2020. That's when my tool started failing similarly to yours.

https://composer.github.io/pubkeys.html

I should mention. My action is specifically bombing out on step 4/11 of the Dockerfile being built. Here's the isolated step from that occurring:

```
Step 4/11 : RUN php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
118
 ---> Running in 97c8a2657ce2
119
Installer corrupt
```

**Comment by pramser** [comment]
I pulled the code locally a minute ago and tried updating the SHA in my Dockerfile. Worked like a charm. I'll create a pull request and link it to here.
